---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# nhdR

The goal of nhdR is to provide R tools for interacting with the National Hydrography Dataset.

## Installation

You can install nhdR from github with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("jsta/nhdR")
```

## Usage
### Load package

```{r }
library(nhdR)
```

### NHD

```{r eval=FALSE}
nhd_get(state = c("DC", "HI"))
```

```{r }
nhd_list(state = "DC")
```

```{r }
nhd_info(state = "DC", layer_name = "NHDWaterbody")
```

```{r }
nhd_load(state = "DC", layer_name = "NHDWaterbody")
```


### NHD Plus

Unlike the standard NHD, the NHD-Plus exports are organized by vector processing unit (vpu). A vpu map can be found [here](http://www.horizon-systems.com/NHDPlus/NHDPlusV2_data.php).

```{r eval=FALSE}
# get a vpu export
nhd_plus_get(vpu = 4)
```

```{r }
# list layers
nhd_plus_list(vpu = 4)
```

```{r eval=FALSE}
# get layer info
nhd_plus_info(vpu = 4, "NHDWaterbody")
```

```{r echo=FALSE}
info <- capture.output(nhd_plus_info(vpu = 4, "NHDWaterbody"))
# gsub("/home/jose", "~", info)
info[2:length(info)]
```

```{r }
# load layer
dt <- nhd_plus_load(vpu = 4, "NHDWaterbody")
```
